{
  "name": "Bumper",
  "version": "1.1.0",
  "slug": "bumper",
  "codenotary": "djhhui@gmail.com",
  "description": "这是一个扫地机器人的局域网服务器。关注微信号：<老王杂谈说> 获取更多内容吧",
  "url": "https://github.com/Desmond-Dong/hassio-addons",
  "arch": [
    "armhf",
    "armv7",
    "aarch64",
    "amd64",
    "i386"
  ],
  "startup": "application",
  "boot": "auto",
  "ports": {
    "443/tcp": 443,
    "8007/tcp": 8007,
    "8883/tcp": 8883,
    "5223/tcp": 5223
  },
  "ports_description": {
    "443/tcp": "HTTPS port",
    "8007/tcp": "Bumper server port",
    "8883/tcp": "MQTT over SSL port",
    "5223/tcp": "Push notifications port"
  },
  "options": {
    "server_ip": "",
    "server_port": 8007,
    "web_port": 8080,
    "debug_logs": false,
    "enable_ssl": true  
  },
  "schema": {
    "server_ip": "str",
    "server_port": "port",
    "web_port": "port",
    "debug_logs": "bool",
    "enable_ssl": "bool"  
  },
  "init": false
}