build_from:
  aarch64: "ghcr.nju.edu.cn/hassio-addons/base-aarch64:14.0.2"
  amd64: "ghcr.nju.edu.cn/hassio-addons/base-amd64:14.0.2"
  armhf: "ghcr.nju.edu.cn/hassio-addons/base-armhf:14.0.2"
  armv7: "ghcr.nju.edu.cn/hassio-addons/base-armv7:14.0.2"
  i386: "ghcr.nju.edu.cn/hassio-addons/base-i386:14.0.2"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bumper"
  org.opencontainers.image.description: "A local server for Ecovacs Deebot devices"
  org.opencontainers.image.source: "https://github.com/yourusername/hassio-addons"
  org.opencontainers.image.licenses: "Apache-2.0"

args:
  TEMPIO_VERSION: "2021.09.0"
  S6_OVERLAY_VERSION: "3.1.5.0" 